platform:ios, '8.0'

use_frameworks!

def pods
    pod 'SnapKit', '~> 0.18.0'
    pod 'Alamofire', '~> 3.3.0'
    pod 'ObjectMapper', '~> 1.2.0'
    pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'DrawerController', '~> 1.1.0'
    pod 'Kingfisher', '~> 1.9.1'
    pod 'KVOController', '~> 1.0.3'
    pod 'YYText', '~> 0.9.18'
    pod 'SVProgressHUD', '~> 1.1.3'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'KeychainSwift', '~> 3.0.11'
    pod 'INSImageView', '~> 0.1.5'
    pod 'CXSwipeGestureRecognizer', '~> 1.0.2'
    pod 'Shimmer', '~> 1.0.2'
    #pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'SwiftyJSON'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'CocoaAsyncSocket'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'coreFrame' do
    pods
end